#
# SPDX-FileCopyrightText: 2026 Anton Lem <antonlem78@gmail.com>
# SPDX-License-Identifier: Apache-2.0
#

# codecov.yml
coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 1%
    patch:
      default:
        target: 75%
ignore:
  - "**/generated/**"
  - "**/examples/**"
