name: LemonAnt Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.6-eclipse-temurin-21

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Verify build
        run: mvn -B verify
