name: LemonAnt Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.6-eclipse-temurin-21

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Verify build
        run: mvn -B verify

  publish-snapshot:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.6-eclipse-temurin-21

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Publish snapshot to GitHub Packages
        run: mvn deploy --settings .github/maven-settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
