name: 02-Compatibility Test

on:
  workflow_run:
    workflows: ["01-Build Artifacts"]
    types: [ completed ]

permissions:
  contents: read
  actions: read

jobs:
  compat-matrix:
    # Run only if 01 succeeded and base event was push(main) or release
    if: ${{ github.event.workflow_run.conclusion == 'success' && ((github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main') || github.event.workflow_run.event == 'release') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        vendor: [ temurin, microsoft ]
        java:   [ 11, 17, 21, 23 ]
        exclude:
          - vendor: microsoft
            java: 23
    steps:
      - name: Checkout at triggering commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Download dist, deps, and runner from 01
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p dist deps runner
          gh run download ${{ github.event.workflow_run.id }} \
            -R ${{ github.event.workflow_run.repository.full_name }} \
            --name gpf-dist --dir dist
          gh run download ${{ github.event.workflow_run.id }} \
            -R ${{ github.event.workflow_run.repository.full_name }} \
            --name gpf-deps-runtime --dir deps
          gh run download ${{ github.event.workflow_run.id }} \
            -R ${{ github.event.workflow_run.repository.full_name }} \
            --name gpf-runner --dir runner
          echo "Dist:" && ls -l dist || true
          echo "Deps:" && ls -l deps || true
          echo "Runner:" && ls -l runner || true

      - name: Pick main jar
        id: pick
        run: |
          MAIN=$(ls dist/*.jar | grep -v -- '-sources.jar' | grep -v -- '-javadoc.jar' | head -n1)
          echo "main=$MAIN" >> "$GITHUB_OUTPUT"
          echo "Main: $MAIN"

      - name: Set up Java ${{ matrix.java }} (${{ matrix.vendor }})
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.vendor }}
          java-version: ${{ matrix.java }}
          cache: maven

      - run: java -version

      - name: Run precompiled Runner on this JVM
        run: |
          java -cp "${{ steps.pick.outputs.main }}:deps/*:runner" Runner
