name: Build once → Run many (compat) + Snapshot publish

on:
  push:
    branches: [ main ]   # post-merge проверка
  workflow_dispatch:      # ручной запуск по желанию

permissions:
  contents: read
  packages: write

jobs:
  build-baseline:
    name: Build baseline JAR (one compile)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17 (baseline)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build once (light)
        run: |
          # Один раз собираем артефакт (байткод у тебя release=11)
          mvn -B -q -Dci=true -Dskip-quality-gates=true clean verify
          ls -l target

      - name: Upload built JAR
        uses: actions/upload-artifact@v4
        with:
          name: gpf-jar
          path: target/*.jar
          if-no-files-found: error

  compat-matrix:
    name: Runtime compat — JDK ${{ matrix.java }} / ${{ matrix.vendor }}
    needs: build-baseline
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { vendor: temurin,   java: 11 }
          - { vendor: temurin,   java: 17 }
          - { vendor: temurin,   java: 21 }
          - { vendor: temurin,   java: 23 }   # у Temurin есть 23
          - { vendor: microsoft, java: 11 }
          - { vendor: microsoft, java: 17 }
          - { vendor: microsoft, java: 21 }   # у MS 23 нет
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download built JAR
        uses: actions/download-artifact@v4
        with:
          name: gpf-jar
          path: artifact

      - name: Pick JAR path
        id: pick
        run: echo "jar=$(ls artifact/*.jar | head -n1)" >> $GITHUB_OUTPUT

      - name: Set up Java ${{ matrix.java }} (${{ matrix.vendor }})
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.vendor }}
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Show java -version
        run: java -version

      - name: Copy runtime dependencies to ./deps
        run: |
          # Копируем ВСЕ runtime-зависимости проекта в папку deps (без сборки исходников)
          mvn -q -DincludeScope=runtime -DoutputDirectory=deps dependency:copy-dependencies
          ls -l deps || true

      - name: Compile smoke consumer (against lib JAR + deps)
        run: |
          cat > Runner.java <<'JAVA'
          import java.nio.file.*; import java.util.*; import java.util.stream.*;
          import io.github.lemon_ant.globpathfinder.GlobPathFinder;
          import io.github.lemon_ant.globpathfinder.PathQuery;

          public class Runner {
            public static void main(String[] args) {
              PathQuery q = PathQuery.builder()
                  .baseDir(Paths.get("."))
                  .includeGlobs(Set.of("**/*"))
                  .excludeGlobs(Set.of())
                  .allowedExtensions(Set.of())
                  .onlyFiles(false)
                  .maxDepth(Integer.MAX_VALUE)
                  .build();

              try (Stream<Path> s = GlobPathFinder.findPaths(q)) {
                System.out.println("OK " + s.limit(1).count());
              }
            }
          }
          JAVA
          javac -cp "${{ steps.pick.outputs.jar }}:deps/*:." Runner.java

      - name: Run smoke on this JVM
        run: java -cp "${{ steps.pick.outputs.jar }}:deps/*:." Runner

  publish-snapshot:
    name: Publish SNAPSHOT to GitHub Packages (only if compat passed)
    needs: compat-matrix
    if: ${{ success() }}   # публикация блокируется, если матрица упала
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download built JAR
        uses: actions/download-artifact@v4
        with:
          name: gpf-jar
          path: artifact

      - name: Pick JAR path
        id: pick
        run: echo "jar=$(ls artifact/*.jar | head -n1)" >> $GITHUB_OUTPUT

      - name: Set up Java for deploy (and Maven server creds)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          server-id: github                     # должен совпадать с <id> в pom.xml
          server-username: GITHUB_ACTOR
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read project version
        id: version
        run: |
          VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Deploy exactly that JAR as SNAPSHOT
        run: |
          mvn -B -q deploy:deploy-file \
            -Dfile="${{ steps.pick.outputs.jar }}" \
            -DrepositoryId=github \
            -Durl="https://maven.pkg.github.com/lemon-ant/glob-path-finder" \
            -DgroupId=io.github.lemon-ant \
            -DartifactId=glob-path-finder \
            -Dversion="${{ steps.version.outputs.version }}" \
            -Dpackaging=jar \
            -DpomFile=pom.xml
