name: LemonAnt PR Verify

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.java'
      - '**/pom.xml'
      - '**/src/**/resources/**'
      - '.github/workflows/*.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }} # Per PR branch
  cancel-in-progress: true

jobs:
  verify:
    name: Verify PR build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build and verify
        run: mvn -B -ntp clean verify -Dci=true
